baseURL = "http://qsyqian.github.io/"
#languageCode = "en-us"
#title = "My New Hugo Site"

LanguageCode= "fr-FR"
Title= "Welcome!"
paginate = 5
DisqusShortname = "sqian"
Copyright = "All rights reserved - 2019"
canonifyurls = true

[params]
  description = "this is my description"
  cover = "images/cover.jpg"
  author = "Shuangyang Qian"
  authorlocation = "Beijing, China"
  authorwebsite = "http://github.com/qsyqian"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "qsyqian"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  githubName = "qsyqian"
  #twitterName = "vjeantet"
  # facebookName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
